### PR TITLE
Taglastprepackage

### PR DESCRIPTION
**Pull request by rminnich**

### CODE REVIEW

**Comment by rminnich** [comment]
Won't squash this of course, so bisect is easier.

**Review by brho — APPROVED** [review]

**Comment by rminnich** [comment]
oops, it's broken, hold on.

**Comment by brho** [comment]
On 2022-04-25 at 13:14 ron minnich ***@***.***> wrote:
> oops, it's broken, hold on.

Ack.  on my end, "cpud -new" works, but "cpu -new" has issues.  i'm
guessing some diff in the old is not in the new.

**Comment by rminnich** [comment]
harder than it looks, need to take it slower.

**Pull request closed without merging**
