### PR TITLE
Maybe deal with PWD is not a directory in the remote namespace

### PR DESCRIPTION
**Pull request by brho**
PWD on the cpu client side might not exist in the namespace created by
cpud -remote.  For instance, if you run cpu from /tmp/foo, and that is
not exported in the 9p namespace= parameter, the command will fail with
something like:

	CPUD(as remote):chdir /tmp/foo: no such file or directory

Signed-off-by: Barret Rhoden <brho@google.com>

### CODE REVIEW

**Review by rminnich — APPROVED** [review]
nice checking the IsDir thing :-)

**Comment by rminnich** [comment]
let's think about this a bit more?

**Comment by brho** [comment]
yeah, i think maybe not for this one.  too many subtleties.  i'll change it to be a more verbose error.

**Comment by brho** [comment]
changed it to print a more verbose notice.  though not sure if this is excessive or not.

still wonder if we should put PWD into the *default* namespace argument.

**Comment by rminnich** [comment]
thinking about it ... I think this cure may be worse than the disease. maybe the real fix is just a more useful error message: have the session stat ($PWD) and point out that it's not in the namespace?

**Comment by brho** [comment]
yeah, the loud error doesn't break anything, and should at least help diagnose the issue.  i updated the patch to just print and error out.

**Review by rminnich — APPROVED** [review]

**Review by rminnich — APPROVED** [review]

**Pull request merged**
