### PR TITLE
Add Github Actions for building/publishing docker, building go, and building rust

### PR DESCRIPTION
**Pull request by ericvh**
Signed-off-by: Eric Van Hensbergen <ericvh@gmail.com>

### CODE REVIEW

**Comment by ericvh** [comment]
Docker failed on pushing to ghcr.io, but I think it might be an actions permission problem.  Closest thing I can see from looking at one of my projects is: 
Screen Shot 2022-10-03 at 4 09 59 PM

**Comment by rminnich** [comment]
we have those settings aready, I'll look too to see what else might be going on.

**Comment by rminnich** [comment]
https://stackoverflow.com/questions/72248956/github-action-with-docker-makes-error-exporting-to-image-403-forbidden-error


```

Adding the below permissions to the build job fixed this issue for me. I am not sure it will work for anyone, but this question was the first I found when looking for a solution. Hopefully it can help future people:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
```

**Comment by rminnich** [comment]
https://stackoverflow.com/questions/72248956/github-action-with-docker-makes-error-exporting-to-image-403-forbidden-error


```

Adding the below permissions to the build job fixed this issue for me. I am not sure it will work for anyone, but this question was the first I found when looking for a solution. Hopefully it can help future people:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
```

**Comment by ericvh** [comment]
yup, still failed for me, I think there is owner kung-fu required.  I'll see about gating publishing the image to be only if you have permission.

**Review by rminnich — APPROVED** [review]

**Pull request merged**
