### PR TITLE
Update the code to use templatefs lib funcs smoothly

### PR DESCRIPTION
**Pull request by v-thakkar**
There have been a bunch of changes in the core p9 library functions as well as in the filesystem code. Now that this repo is importing restructured templatefs, let's update the code accordingly. This commit also fixes a bunch of build errors.

Signed-off-by: Vaishali Thakkar <vaishali.thakkar@9elements.com>

### CODE REVIEW

**Review by nasirhm — APPROVED** [review]
LGTM

**Comment by fhs** [comment]
Still doesn't build for me:
```
$ GO111MODULE=off go build ./...
# github.com/u-root/cpu/cmds/cpu
cmds/cpu/srv.go:62:51: not enough arguments in call to p9.NewServer(&cpu9p{...}).Handle
	have (net.Conn)
	want (io.ReadCloser, io.WriteCloser)
```

This fixes it:
```diff
diff --git a/cmds/cpu/srv.go b/cmds/cpu/srv.go
index 65887c3..3981a5e 100644
--- a/cmds/cpu/srv.go
+++ b/cmds/cpu/srv.go
@@ -59,7 +59,7 @@ func srv(l net.Listener, root string, n nonce, deadline time.Time) {
                        log.Fatalf("srv: %v", err)
                }
        }
-       if err := p9.NewServer(&cpu9p{path: root}).Handle(c); err != nil {
+       if err := p9.NewServer(&cpu9p{path: root}).Handle(c, c); err != nil {
                log.Fatalf("Serving cpu remote: %v", err)
        }
 }
```

**Comment by hugelgupf** [comment]
Does this need a vendor update? (I've been meaning to switch this repo to modules as well)

**Comment by fhs** [comment]
I didn't need a vendor update. Switching to modules would be good.

**Comment by v-thakkar** [comment]
> Still doesn't build for me:
> 
> ```diff
> diff --git a/cmds/cpu/srv.go b/cmds/cpu/srv.go
> index 65887c3..3981a5e 100644
> --- a/cmds/cpu/srv.go
> +++ b/cmds/cpu/srv.go
> @@ -59,7 +59,7 @@ func srv(l net.Listener, root string, n nonce, deadline time.Time) {
>                         log.Fatalf("srv: %v", err)
>                 }
>         }
> -       if err := p9.NewServer(&cpu9p{path: root}).Handle(c); err != nil {
> +       if err := p9.NewServer(&cpu9p{path: root}).Handle(c, c); err != nil {
>                 log.Fatalf("Serving cpu remote: %v", err)
>         }
>  }
> ```

Yes, I was aware of this error too. But wanted to send a separate PR for the same. Although above commit looks good for now as well. :+1:

**Comment by hugelgupf** [comment]
I subsumed your commit in #16 and am fixing the CircleCI infra there, as well, so we can turn on presubmits that ensure every PR builds.

**Comment by hugelgupf** [comment]
Also, just FYI, I just changed the default branch to main, for those of you who have already cloned the repo.

**Pull request closed without merging**
